### ISSUE TITLE
Show stop info

### ISSUE THREAD

**Issue by br3ndonland** [growwithgooglema/gwg-mbta#17]
### Current behavior

The application displays information on MBTA stops available near the searched location, but doesn't have further options.

![screen-shot-2018-04-15-at-14 16 59-iphone-6s-small](https://user-images.githubusercontent.com/26674818/38781782-87b0224a-40b8-11e8-9eb8-ea4ab825931e.png)

### Suggested updates

It would be very helpful to provide further information about the stops. This could be either by returning a stop list, dropping pins at the stops (might be too many pins), or shading/coloring the map.

**Comment by AbdouSeck** [comment]
I've been fighting the urge to add stops (as additional markers) to the map, because I fear that that would sort of pollute the map. But the idea of only showing the stops on the map does sound pretty good--essentially instead of showing the searched location, we show markers for stops within a 0.5 mile radius from it. This will mean making some very important tweaks to the current `google-maps.js` script, but I think it's very much feasible. @jethridge13 @br3ndonland @noirfatale does this sound like a good idea?

**Comment by br3ndonland** [comment]
I think it would be great @AbdouSeck . Thanks for continuing to tackle these challenging features. As I mentioned in Slack, I should be able to help more with the JavaScript at some point in the next few weeks.

Let's keep this new stop list feature on the `dev` branch for a while, until we have it working well and agree on the implementation.

**Comment by jethridge13** [comment]
I like the idea of including the stops. If we find that showing the stops becomes too crowded after a certain zoom level, we could perhaps include a list of the stops in a sidebar with addresses (similar to how Google Maps shows search results) and then hide the markers once the user zooms out past a certain threshold.

**Comment by br3ndonland** [comment]
Great idea @jethridge13 !
